#!/usr/bin/env python

# This amulet test deploys the bundles.yaml file in this directory.

import unittest

from base import GangliaBundleTest


class GangliaTrustyBundleTest(GangliaBundleTest):
    """ Ganglia Trusty Test """
    bundle_name = 'bundle-trusty.yaml'


if __name__ == '__main__':
    unittest.main()
